In [3]:
print("Exploring the facebook AI Simility Search...")

Exploring the facebook AI Simility Search...


In [4]:
pip freeze > requirements.txt

Note: you may need to restart the kernel to use updated packages.


In [5]:
pip install faiss-cpu

  Using cached faiss_cpu-1.12.0-cp313-cp313-win_amd64.whl.metadata (5.2 kB)
  Using cached numpy-2.3.2-cp313-cp313-win_amd64.whl.metadata (60 kB)
Using cached faiss_cpu-1.12.0-cp313-cp313-win_amd64.whl (18.2 MB)
Using cached numpy-2.3.2-cp313-cp313-win_amd64.whl (12.8 MB)

   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy

In [6]:
data = """Helping Millions of Students Succeed
Sudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.

In 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron continued to offer some of the most affordable and accessible tech courses in the world.

The Entrepreneur and Teacher: Sudhanshu's Dual Legacy
Sudhanshu's journey isn't just one of entrepreneurial success; it's also a story of dedication to teaching. Throughout his career, he has remained a passionate educator, constantly looking for ways to empower others through knowledge. Whether teaching courses in Big Data, Data Science, or programming, Sudhanshu has always sought to make complex subjects accessible to learners at all levels.

His commitment to affordable education has earned him the respect and admiration of countless students. Many credit Sudhanshu with changing their lives, helping them secure jobs, improve their skills, and break free from the limitations of their backgrounds."""

In [7]:
len(data)
data

"Helping Millions of Students Succeed\nSudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.\n\nIn 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron continued to offer some of the most affordable and accessible tech courses in the world.\n\nThe Entrepreneur and Teacher: Sudhanshu's Dual Legacy\nSudhanshu's journey isn't just one of entrepreneurial success; it's also a story of dedication to teaching. Throughout his career, he has remained a passionate educa

In [8]:
clean_data = data.strip()

In [9]:
len(clean_data)
clean_data

"Helping Millions of Students Succeed\nSudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.\n\nIn 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron continued to offer some of the most affordable and accessible tech courses in the world.\n\nThe Entrepreneur and Teacher: Sudhanshu's Dual Legacy\nSudhanshu's journey isn't just one of entrepreneurial success; it's also a story of dedication to teaching. Throughout his career, he has remained a passionate educa

In [10]:
max_char = 300
overlap = 100
chunks = []
i=0

while i<len(clean_data):
    pices = clean_data[i:i+max_char]
    chunks.append(pices)
    i = i + (max_char - overlap)


In [11]:
len(chunks)

8

In [12]:
chunks

["Helping Millions of Students Succeed\nSudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive j",
 "nts from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.\n\nIn 2022, iNeuron was a",
 ' saw iNeuron as a lifeline—an opportunity to rise above their circumstances.\n\nIn 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron continued to off',
 "one, Sudhanshu remained focused on his mission. Even after the acquisition, iN

In [13]:
pip install requests

  Using cached requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
  Using cached charset_normalizer-3.4.3-cp313-cp313-win_amd64.whl.metadata (37 kB)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
  Using cached urllib3-2.5.0-py3-none-any.whl.metadata (6.5 kB)
  Using cached certifi-2025.8.3-py3-none-any.whl.metadata (2.4 kB)
Using cached requests-2.32.5-py3-none-any.whl (64 kB)
Using cached charset_normalizer-3.4.3-cp313-cp313-win_amd64.whl (107 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Using cached urllib3-2.5.0-py3-none-any.whl (129 kB)
Using cached certifi-2025.8.3-py3-none-any.whl (161 kB)

   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   -------------------------------- ------- 4/5 [requests]
   ---------------------------------------- 5/5 [requests]

Not

In [14]:

import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer euri-7888e319ae7f089816c1e629020e75b00038fca1978612ab6f6213431f771c58"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    embedding = np.array(data['data'][0]['embedding'])
    
    return embedding



In [15]:
for i in chunks:
    embedding = generate_embeddings(i)
    print(embedding)

[ 0.00644781 -0.00417461  0.05262613 ... -0.00740993 -0.00933416
  0.01381534]
[-0.03353467  0.01464209  0.04098682 ... -0.02121102 -0.00963949
 -0.00190789]
[-0.03021665 -0.02769395  0.00051569 ... -0.01901084  0.00820923
  0.03057902]
[-0.01145488 -0.01112982  0.05018822 ... -0.04298504  0.01322966
  0.01812497]
[ 0.01886767 -0.00685348  0.07775307 ... -0.02177137  0.00743675
  0.00906612]
[-0.01484207 -0.02882594  0.04816102 ... -0.02882594 -0.00869574
 -0.01159222]
[ 0.00854274 -0.01758461  0.06537279 ...  0.00447614 -0.01841649
  0.00040294]
[ 0.02617518  0.01859544  0.04257006 ... -0.0121546  -0.08066177
  0.00675613]


In [16]:
for idx, chunk in enumerate(chunks):
    embedding = generate_embeddings(chunk)
    print(f"Chunk {idx+1} embedding: {embedding}")

Chunk 1 embedding: [ 0.00642448 -0.00413841  0.05262205 ... -0.00740935 -0.00933343
  0.01380122]
Chunk 2 embedding: [-0.03358429  0.01465346  0.0410076  ... -0.0212075  -0.00962409
 -0.00191102]
Chunk 3 embedding: [-0.03021665 -0.02769395  0.00051569 ... -0.01901084  0.00820923
  0.03057902]
Chunk 4 embedding: [-0.01145488 -0.01112982  0.05018822 ... -0.04298504  0.01322966
  0.01812497]
Chunk 5 embedding: [ 0.01886767 -0.00685348  0.07775307 ... -0.02177137  0.00743675
  0.00906612]
Chunk 6 embedding: [-0.0148782  -0.02887305  0.04820588 ... -0.02882257 -0.00871365
 -0.01156563]
Chunk 7 embedding: [ 0.00850178 -0.0175793   0.06540421 ...  0.00450997 -0.01844931
  0.00041142]
Chunk 8 embedding: [ 0.02614528  0.01865682  0.04253754 ... -0.0121591  -0.08064892
  0.00674862]


In [17]:
embedding_list = []
meta = []

for idx, chunk in enumerate(chunks):
    vec = generate_embeddings(chunk)
    embedding_list.append(vec.astype('float32'))

    meta.append({"id":idx, "text": chunk})
    


In [18]:
embedding_list

[array([ 0.0064576 , -0.00415831,  0.0526523 , ..., -0.00737732,
        -0.0093146 ,  0.0138284 ], shape=(1536,), dtype=float32),
 array([-0.03358296,  0.01465288,  0.04100598, ..., -0.02120666,
        -0.00964441, -0.00189887], shape=(1536,), dtype=float32),
 array([-0.03025641, -0.02773272,  0.00056251, ..., -0.01900437,
         0.00810091,  0.0304795 ], shape=(1536,), dtype=float32),
 array([-0.0114289 , -0.01118185,  0.05011031, ..., -0.04298513,
         0.01321669,  0.018099  ], shape=(1536,), dtype=float32),
 array([ 0.01886726, -0.00683431,  0.07775135, ..., -0.02174553,
         0.00746195,  0.00906592], shape=(1536,), dtype=float32),
 array([-0.01483842, -0.02884407,  0.04817439, ..., -0.02876836,
        -0.00870621, -0.01158305], shape=(1536,), dtype=float32),
 array([ 0.00851466, -0.01757947,  0.06535367, ...,  0.00452281,
        -0.01844949,  0.00040562], shape=(1536,), dtype=float32),
 array([ 0.026201  ,  0.01860837,  0.04254445, ..., -0.01218681,
        -0.0806620

In [19]:
meta

[{'id': 0,
  'text': "Helping Millions of Students Succeed\nSudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive j"},
 {'id': 1,
  'text': "nts from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.\n\nIn 2022, iNeuron was a"},
 {'id': 2,
  'text': ' saw iNeuron as a lifeline—an opportunity to rise above their circumstances.\n\nIn 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron continued to off'},
 {'id': 3,
  'tex

In [20]:
type(embedding_list)

list

In [21]:
xb = np.vstack(embedding_list)

In [22]:
import faiss

In [23]:
faiss.normalize_L2(xb)

In [24]:
d = xb.shape[1]

In [25]:
d

1536

In [26]:
index = faiss.IndexFlatIP(d)
index.add(xb)

In [27]:
index

<faiss.swigfaiss_avx2.IndexFlatIP; proxy of <Swig Object of type 'faiss::IndexFlatIP *' at 0x00000140DF007C00> >

In [28]:
index_path = "index_akash.faiss"
meta_path = "meta_akash.jsonl"

In [29]:
faiss.write_index(index, index_path)

In [30]:
import os, json

In [35]:
with open(meta_path, "w") as f:
    for item in meta:
        f.write(json.dumps(item)+"\n")

In [36]:
query = "who is sudhanshu"
q = generate_embeddings(query).astype("float32").reshape(1, -1)
faiss.normalize_L2(q)
index.search(q, 5)

(array([[0.53641677, 0.5320464 , 0.523605  , 0.50172275, 0.4004469 ]],
       dtype=float32),
 array([[6, 5, 3, 4, 0]]))

In [2]:
# enumeration concept in python
fullname = ['Akash', 'Yadav', 'from', 'Bhopal']
for i in enumerate(fullname):
    print(i) 

(0, 'Akash')
(1, 'Yadav')
(2, 'from')
(3, 'Bhopal')


In [34]:
# in ref of above code
