In [2]:
print("Hello, World!")

Hello, World!


In [3]:
data = """

Gandhi was born on 19 June 1970 at Holy Family Hospital in Delhi.[12] He was the first of two children born to Rajiv Gandhi, who later served as the 6th prime minister of India, and Sonia Gandhi, who went on to become the president of the Indian National Congress. As the grandson of former prime minister Indira Gandhi, his lineage is deeply rooted in Indian political history. His paternal grandfather, Feroze Gandhi, hailed from Gujarat and was of Parsi descent.[13] Furthermore, he is the great-grandson of India's inaugural prime minister, Jawaharlal Nehru.

Gandhi completed his elementary education at St. Columba's School in New Delhi.[14] He then attended The Doon School in Dehradun (an elite all-boys' boarding school, also the alma mater of his father, Rajiv Gandhi) from 1981 to 1983.[15] At Doon, Gandhi studied alongside notable contemporaries, including former Congress members Jyotiraditya Scindia and Jitin Prasada.[16][17] Following the assassination of Indira Gandhi by Sikhs in her personal guard on 31 October 1984, his father entered politics and became the 6th prime minister of India. Due to security threats from Sikh extremists, Gandhi and his sister Priyanka were home-schooled, taking examinations under the supervision of teachers.[18] Spending their childhood away from media attention, Gandhi and his sister kept low profiles, appearing with their parents at a handful of public occasions.[19]

Gandhi joined St. Stephen's College, Delhi, an affiliated college of the University of Delhi, in 1989 for his undergraduate education.[20] Gandhi's academic performance in Class XII, with a score of 61 per cent in the CBSE school certificate, was perceived as not particularly strong.[21] He gained admission to St. Stephen's College for BA (Honors) History through the sports quota, which granted a 10 per cent advantage in exam scores to promising athletes; per National Rifle Association of India testimonials, Gandhi stood 4th in the 32nd National Shooting Competition held in New Delhi from 26 December 1988 to 5 January 1989.[21] Gandhi had finished fourth in the Centre Fire Pistol 25 M (Indian Rule) Men's civilian event with a score of 371 out of 400 points.[21] By July 1989, Gandhi had won eight national awards. In 1991, following the assassination of Rajiv Gandhi by the LTTE during an election rally, Gandhi left St. Stephen's and moved to Harvard University. Due to security concerns, he subsequently relocated to Rollins College in Florida. He further went on to obtain an Master of Philosophy (MPhil) in Development Studies, from Trinity College, Cambridge in 1995.[22][23] Following his father and former prime minister Rajiv Gandhi's assassination in 1991, there was a heightened threat perception to the family, those closest to Gandhi were paranoid about his safety and might have forced him to take cover under the misleading surname "Vinci".[24]

After completing higher education, Gandhi worked at the Monitor Group, a management consulting firm set up by Michael Porter of Harvard Business School, in London for three years.[25] In 2002, he returned to India and established his technology consultancy, Backops Services Private Ltd, in Mumbai, where he served as one of the directors of the firm.[26] Subsequently, he founded BackOps UK, a company that secured defence contracts from foreign suppliers.[27]

"""

In [4]:
len(data)

3362

In [5]:
clean_data = data.strip()

In [6]:
len(clean_data)

3358

In [7]:
clean_data

'Gandhi was born on 19 June 1970 at Holy Family Hospital in Delhi.[12] He was the first of two children born to Rajiv Gandhi, who later served as the 6th prime minister of India, and Sonia Gandhi, who went on to become the president of the Indian National Congress. As the grandson of former prime minister Indira Gandhi, his lineage is deeply rooted in Indian political history. His paternal grandfather, Feroze Gandhi, hailed from Gujarat and was of Parsi descent.[13] Furthermore, he is the great-grandson of India\'s inaugural prime minister, Jawaharlal Nehru.\n\nGandhi completed his elementary education at St. Columba\'s School in New Delhi.[14] He then attended The Doon School in Dehradun (an elite all-boys\' boarding school, also the alma mater of his father, Rajiv Gandhi) from 1981 to 1983.[15] At Doon, Gandhi studied alongside notable contemporaries, including former Congress members Jyotiraditya Scindia and Jitin Prasada.[16][17] Following the assassination of Indira Gandhi by Sikh

In [8]:
with open("Rahul_info.txt", "w") as file:
    file.write(clean_data)

In [9]:
len(clean_data)

3358

In [10]:
max_char = 300 # in one line i want only 1000 chars
overlap = 100 # it is for contex may 1000 char brak the meaning of sentance
chunks = []

i=0
while i<len(clean_data):
    piece = clean_data[i:max_char+i]
    # print("data:", piece)
    # print(len(piece))
    chunks.append(piece)
    i = i + max_char - overlap

In [11]:
len(chunks)

17

In [12]:
chunks

['Gandhi was born on 19 June 1970 at Holy Family Hospital in Delhi.[12] He was the first of two children born to Rajiv Gandhi, who later served as the 6th prime minister of India, and Sonia Gandhi, who went on to become the president of the Indian National Congress. As the grandson of former prime min',
 'went on to become the president of the Indian National Congress. As the grandson of former prime minister Indira Gandhi, his lineage is deeply rooted in Indian political history. His paternal grandfather, Feroze Gandhi, hailed from Gujarat and was of Parsi descent.[13] Furthermore, he is the great-g',
 "her, Feroze Gandhi, hailed from Gujarat and was of Parsi descent.[13] Furthermore, he is the great-grandson of India's inaugural prime minister, Jawaharlal Nehru.\n\nGandhi completed his elementary education at St. Columba's School in New Delhi.[14] He then attended The Doon School in Dehradun (an eli",
 "ation at St. Columba's School in New Delhi.[14] He then attended The Doon School 

In [13]:
for idx,stm in enumerate(chunks):
    print(f"id:{idx} data: {stm}")

id:0 data: Gandhi was born on 19 June 1970 at Holy Family Hospital in Delhi.[12] He was the first of two children born to Rajiv Gandhi, who later served as the 6th prime minister of India, and Sonia Gandhi, who went on to become the president of the Indian National Congress. As the grandson of former prime min
id:1 data: went on to become the president of the Indian National Congress. As the grandson of former prime minister Indira Gandhi, his lineage is deeply rooted in Indian political history. His paternal grandfather, Feroze Gandhi, hailed from Gujarat and was of Parsi descent.[13] Furthermore, he is the great-g
id:2 data: her, Feroze Gandhi, hailed from Gujarat and was of Parsi descent.[13] Furthermore, he is the great-grandson of India's inaugural prime minister, Jawaharlal Nehru.

Gandhi completed his elementary education at St. Columba's School in New Delhi.[14] He then attended The Doon School in Dehradun (an eli
id:3 data: ation at St. Columba's School in New Delhi.[14] He th

In [14]:
pip install requests

Note: you may need to restart the kernel to use updated packages.


In [15]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [16]:

import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer euri-6dd7197ccd0b327d27be9f69d9a57d260bb12326878fb3f64594cc3dd9638458"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    embedding = np.array(data['data'][0]['embedding'])
    
    return embedding


In [17]:
for sentance in chunks:
    embedding = generate_embeddings(sentance)
    # print(embedding)

In [18]:
emb_list = []
meta_list = []

for idx, statement in enumerate(chunks):
    vec = generate_embeddings(statement)
    emb_list.append(vec.astype("float32"))

    meta_list.append({"id": idx, "text": statement})

In [19]:
emb_list

[array([ 0.0492195 ,  0.02831699,  0.00977094, ...,  0.0364808 ,
         0.01662341, -0.00802085], shape=(1536,), dtype=float32),
 array([ 0.03508653, -0.02827322, -0.02417299, ...,  0.0017301 ,
         0.01577874, -0.02992555], shape=(1536,), dtype=float32),
 array([ 0.02318017, -0.04631834, -0.00268099, ...,  0.0157474 ,
         0.02065009, -0.03739482], shape=(1536,), dtype=float32),
 array([ 0.02975772, -0.01846481,  0.04899664, ...,  0.01561882,
         0.03476667, -0.01855588], shape=(1536,), dtype=float32),
 array([ 0.02154214, -0.01141428, -0.00260283, ...,  0.02162936,
         0.02773442, -0.02483451], shape=(1536,), dtype=float32),
 array([ 0.02050474,  0.02471623,  0.01587321, ...,  0.00788134,
         0.03420036, -0.03627847], shape=(1536,), dtype=float32),
 array([ 0.03984671, -0.00276261, -0.00548768, ..., -0.0034165 ,
         0.01686978, -0.01099414], shape=(1536,), dtype=float32),
 array([ 0.02736814, -0.02695858,  0.03245148, ..., -0.00270881,
         0.0100522

In [20]:
meta_list

[{'id': 0,
  'text': 'Gandhi was born on 19 June 1970 at Holy Family Hospital in Delhi.[12] He was the first of two children born to Rajiv Gandhi, who later served as the 6th prime minister of India, and Sonia Gandhi, who went on to become the president of the Indian National Congress. As the grandson of former prime min'},
 {'id': 1,
  'text': 'went on to become the president of the Indian National Congress. As the grandson of former prime minister Indira Gandhi, his lineage is deeply rooted in Indian political history. His paternal grandfather, Feroze Gandhi, hailed from Gujarat and was of Parsi descent.[13] Furthermore, he is the great-g'},
 {'id': 2,
  'text': "her, Feroze Gandhi, hailed from Gujarat and was of Parsi descent.[13] Furthermore, he is the great-grandson of India's inaugural prime minister, Jawaharlal Nehru.\n\nGandhi completed his elementary education at St. Columba's School in New Delhi.[14] He then attended The Doon School in Dehradun (an eli"},
 {'id': 3,
  'text':

In [21]:
# with open("Rahul_embedding.txt", "w") as file:
#     file.write(meta_list)


In [22]:
type(emb_list)

list

In [23]:
# conver this embedding list in numpy vector | numpy compatable formate
xb = np.vstack(emb_list)

In [24]:
type(xb)

numpy.ndarray

In [25]:
!pip install faiss-cpu

In [26]:
import faiss

In [27]:
faiss.normalize_L2(xb)

In [28]:
d = xb.shape[1]

In [29]:
d

1536

In [30]:
index = faiss.IndexFlatIP(d)


In [31]:
index # define dymanction of my data in faiss


<faiss.swigfaiss_avx2.IndexFlatIP; proxy of <Swig Object of type 'faiss::IndexFlatIP *' at 0x000002395F3B1830> >

In [32]:
index.add(xb) # store the data in the Facebook AI similarty search

In [33]:
# i want to save this data in disk insted of ram
index_path = "index_rahulghandhi.faiss"
meta_path = "meta_rahulghandi_info.jsonl"

In [34]:
faiss.write_index(index, index_path)

In [35]:
import json

In [36]:
with open(meta_path, 'w') as file:
    for item in meta_list:
        file.write(json.dumps(item)+"\n")

In [37]:
# searching opration
query = "who is rahul ghandi"

# convert this query into embedding
Q = generate_embeddings(query).astype("float32").reshape(1, -1)
faiss.normalize_L2(Q)
index.search(Q, 3)


(array([[0.5243255 , 0.46944407, 0.46106553]], dtype=float32),
 array([[ 0,  2, 11]]))