In [12]:
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.g_VJv7zn5FN96GDMpZCJxV0l4pNGOdq4eIsoerXo-vc


from qdrant_client import QdrantClient

qdrant_client = QdrantClient(
    url="https://30e5b9d3-c104-49d4-98b4-8f84ceae0d34.europe-west3-0.gcp.cloud.qdrant.io:6333", 
    api_key="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.g_VJv7zn5FN96GDMpZCJxV0l4pNGOdq4eIsoerXo-vc",
)

print(qdrant_client.get_collections())

collections=[CollectionDescription(name='RahulGhandi_Info')]


In [13]:
!pip install qdrant_client

In [14]:
qdrant_client

In [15]:
collectionName = "RahulGhandi_Info"

In [16]:
from qdrant_client import models

qdrant_client.recreate_collection(
    collection_name=collectionName, 
    vectors_config=models.VectorParams(
        size=1536, distance=models.Distance.COSINE)
    )

C:\Users\aksydv\AppData\Local\Temp\ipykernel_12636\815178370.py:3: DeprecationWarning: `recreate_collection` method is deprecated and will be removed in the future. Use `collection_exists` to check collection existence and `create_collection` instead.
  qdrant_client.recreate_collection(


True

In [17]:
points = []

In [ ]:
data = """

Gandhi was born on 19 June 1970 at Holy Family Hospital in Delhi.[12] He was the first of two children born to Rajiv Gandhi, who later served as the 6th prime minister of India, and Sonia Gandhi, who went on to become the president of the Indian National Congress. As the grandson of former prime minister Indira Gandhi, his lineage is deeply rooted in Indian political history. His paternal grandfather, Feroze Gandhi, hailed from Gujarat and was of Parsi descent.[13] Furthermore, he is the great-grandson of India's inaugural prime minister, Jawaharlal Nehru.

Gandhi completed his elementary education at St. Columba's School in New Delhi.[14] He then attended The Doon School in Dehradun (an elite all-boys' boarding school, also the alma mater of his father, Rajiv Gandhi) from 1981 to 1983.[15] At Doon, Gandhi studied alongside notable contemporaries, including former Congress members Jyotiraditya Scindia and Jitin Prasada.[16][17] Following the assassination of Indira Gandhi by Sikhs in her personal guard on 31 October 1984, his father entered politics and became the 6th prime minister of India. Due to security threats from Sikh extremists, Gandhi and his sister Priyanka were home-schooled, taking examinations under the supervision of teachers.[18] Spending their childhood away from media attention, Gandhi and his sister kept low profiles, appearing with their parents at a handful of public occasions.[19]

Gandhi joined St. Stephen's College, Delhi, an affiliated college of the University of Delhi, in 1989 for his undergraduate education.[20] Gandhi's academic performance in Class XII, with a score of 61 per cent in the CBSE school certificate, was perceived as not particularly strong.[21] He gained admission to St. Stephen's College for BA (Honors) History through the sports quota, which granted a 10 per cent advantage in exam scores to promising athletes; per National Rifle Association of India testimonials, Gandhi stood 4th in the 32nd National Shooting Competition held in New Delhi from 26 December 1988 to 5 January 1989.[21] Gandhi had finished fourth in the Centre Fire Pistol 25 M (Indian Rule) Men's civilian event with a score of 371 out of 400 points.[21] By July 1989, Gandhi had won eight national awards. In 1991, following the assassination of Rajiv Gandhi by the LTTE during an election rally, Gandhi left St. Stephen's and moved to Harvard University. Due to security concerns, he subsequently relocated to Rollins College in Florida. He further went on to obtain an Master of Philosophy (MPhil) in Development Studies, from Trinity College, Cambridge in 1995.[22][23] Following his father and former prime minister Rajiv Gandhi's assassination in 1991, there was a heightened threat perception to the family, those closest to Gandhi were paranoid about his safety and might have forced him to take cover under the misleading surname "Vinci".[24]

After completing higher education, Gandhi worked at the Monitor Group, a management consulting firm set up by Michael Porter of Harvard Business School, in London for three years.[25] In 2002, he returned to India and established his technology consultancy, Backops Services Private Ltd, in Mumbai, where he served as one of the directors of the firm.[26] Subsequently, he founded BackOps UK, a company that secured defence contracts from foreign suppliers.[27]

"""

'\n\nGandhi was born on 19 June 1970 at Holy Family Hospital in Delhi.[12] He was the first of two children born to Rajiv Gandhi, who later served as the 6th prime minister of India, and Sonia Gandhi, who went on to become the president of the Indian National Congress. As the grandson of former prime minister Indira Gandhi, his lineage is deeply rooted in Indian political history. His paternal grandfather, Feroze Gandhi, hailed from Gujarat and was of Parsi descent.[13] Furthermore, he is the great-grandson of India\'s inaugural prime minister, Jawaharlal Nehru.\n\nGandhi completed his elementary education at St. Columba\'s School in New Delhi.[14] He then attended The Doon School in Dehradun (an elite all-boys\' boarding school, also the alma mater of his father, Rajiv Gandhi) from 1981 to 1983.[15] At Doon, Gandhi studied alongside notable contemporaries, including former Congress members Jyotiraditya Scindia and Jitin Prasada.[16][17] Following the assassination of Indira Gandhi by 

In [58]:
clean_data = data.strip()

In [59]:
len(clean_data)

3358

In [60]:
max_char = 300 # in one line i want only 1000 chars
overlap = 100 # it is for contex may 1000 char brak the meaning of sentance
chunks = []

i=0
while i<len(clean_data):
    piece = clean_data[i:max_char+i]
    # print("data:", piece)
    # print(len(piece))
    chunks.append(piece)
    i = i + max_char - overlap

In [61]:
chunks

['Gandhi was born on 19 June 1970 at Holy Family Hospital in Delhi.[12] He was the first of two children born to Rajiv Gandhi, who later served as the 6th prime minister of India, and Sonia Gandhi, who went on to become the president of the Indian National Congress. As the grandson of former prime min',
 'went on to become the president of the Indian National Congress. As the grandson of former prime minister Indira Gandhi, his lineage is deeply rooted in Indian political history. His paternal grandfather, Feroze Gandhi, hailed from Gujarat and was of Parsi descent.[13] Furthermore, he is the great-g',
 "her, Feroze Gandhi, hailed from Gujarat and was of Parsi descent.[13] Furthermore, he is the great-grandson of India's inaugural prime minister, Jawaharlal Nehru.\n\nGandhi completed his elementary education at St. Columba's School in New Delhi.[14] He then attended The Doon School in Dehradun (an eli",
 "ation at St. Columba's School in New Delhi.[14] He then attended The Doon School 

In [62]:

import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer euri-6dd7197ccd0b327d27be9f69d9a57d260bb12326878fb3f64594cc3dd9638458"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    embedding = np.array(data['data'][0]['embedding'])
    
    return embedding


In [63]:
emb_list = []

for i in chunks:
    emb_list.append(generate_embeddings(i))

In [64]:
emb_list

[array([ 0.04925394,  0.02835355,  0.00976995, ...,  0.03651653,
         0.01660201, -0.00798553], shape=(1536,)),
 array([ 0.03510829, -0.02827431, -0.02411272, ...,  0.00171742,
         0.01576915, -0.02990631], shape=(1536,)),
 array([ 0.02319238, -0.04638477, -0.00270228, ...,  0.01574144,
         0.02062128, -0.03740166], shape=(1536,)),
 array([ 0.02972145, -0.01842502,  0.04896637, ...,  0.0156123 ,
         0.03473196, -0.01853889], shape=(1536,)),
 array([ 0.02154214, -0.01141428, -0.00260283, ...,  0.02162936,
         0.02773442, -0.02483451], shape=(1536,)),
 array([ 0.02048252,  0.0247382 ,  0.01586207, ...,  0.00788129,
         0.03422228, -0.03632248], shape=(1536,)),
 array([ 0.03984594, -0.00276569, -0.00550322, ..., -0.00340392,
         0.01685693, -0.01099392], shape=(1536,)),
 array([ 0.0273437 , -0.02695824,  0.03247516, ..., -0.00270877,
         0.01004008,  0.00416178], shape=(1536,)),
 array([ 0.04906857, -0.03164962,  0.06495819, ..., -0.01386777,
       

In [65]:
embeddings = np.array(emb_list)
embeddings

array([[ 0.04925394,  0.02835355,  0.00976995, ...,  0.03651653,
         0.01660201, -0.00798553],
       [ 0.03510829, -0.02827431, -0.02411272, ...,  0.00171742,
         0.01576915, -0.02990631],
       [ 0.02319238, -0.04638477, -0.00270228, ...,  0.01574144,
         0.02062128, -0.03740166],
       ...,
       [-0.01347099,  0.02295999,  0.02502159, ...,  0.00857822,
         0.05238718, -0.01086575],
       [-0.02853669,  0.05065327,  0.04140309, ..., -0.01062592,
         0.038573  , -0.0233744 ],
       [-0.02186858, -0.00372859,  0.06601395, ..., -0.01533716,
         0.01810718, -0.01912772]], shape=(17, 1536))

In [66]:
points = []

for idx, (chunk, emb) in enumerate(zip(chunks, embeddings)):
    points.append(
        models.PointStruct(
            id= idx,
            vector=emb.astype("float32").tolist(),
            payload={"text": chunk}
        )
    )

In [67]:
points

[PointStruct(id=0, vector=[0.04925394058227539, 0.028353549540042877, 0.00976994726806879, 0.010282598435878754, -0.016917485743761063, 0.0007825323264114559, 0.02285240963101387, 0.03754183650016785, -0.036437664180994034, 0.004002622328698635, 0.021393325179815292, 0.0148471649736166, -0.004034662619233131, -0.03602359816431999, 0.05118624120950699, -0.004133249633014202, 0.004298382438719273, -0.007334854453802109, 0.004046986345201731, 0.06293778121471405, 0.04408799484372139, 0.04404855892062187, 0.06013792008161545, 0.03888261318206787, 0.047282204031944275, -0.005525787360966206, 0.008256640285253525, -0.003083300543949008, 0.026598704978823662, -0.04972715675830841, 0.05445932224392891, 0.013102179393172264, 0.012303626164793968, -0.009321377612650394, 0.00022058785543777049, 0.02265523560345173, 0.00507721770554781, -0.05110737308859825, 0.0016155904158949852, 0.0574563592672348, -0.025317078456282616, -0.050555285066366196, -0.03391384333372116, 0.07626671344041824, 0.0454682

In [68]:
qdrant_client.upsert(
    collection_name=collectionName,
    points=points
)

UpdateResult(operation_id=1, status=<UpdateStatus.COMPLETED: 'completed'>)

In [69]:
query = "who is rahul ghandhi"

In [70]:
q_res = generate_embeddings(query)
q_vec = np.array(q_res).astype("float32")


In [71]:
print(q_res, q_vec)

[ 0.06091465 -0.02027904  0.03315972 ...  0.03650449  0.00434155
  0.00259164] [ 0.06091465 -0.02027904  0.03315972 ...  0.03650449  0.00434155
  0.00259164]


In [72]:
qdrant_client.search(collection_name="RahulGhandi_Info", query_vector=q_vec, limit=3, with_payload=True)

C:\Users\aksydv\AppData\Local\Temp\ipykernel_12636\1741772290.py:1: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  qdrant_client.search(collection_name="RahulGhandi_Info", query_vector=q_vec, limit=3, with_payload=True)


[ScoredPoint(id=0, version=1, score=0.5435468, payload={'text': 'Gandhi was born on 19 June 1970 at Holy Family Hospital in Delhi.[12] He was the first of two children born to Rajiv Gandhi, who later served as the 6th prime minister of India, and Sonia Gandhi, who went on to become the president of the Indian National Congress. As the grandson of former prime min'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=2, version=1, score=0.4917944, payload={'text': "her, Feroze Gandhi, hailed from Gujarat and was of Parsi descent.[13] Furthermore, he is the great-grandson of India's inaugural prime minister, Jawaharlal Nehru.\n\nGandhi completed his elementary education at St. Columba's School in New Delhi.[14] He then attended The Doon School in Dehradun (an eli"}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=11, version=1, score=0.4911508, payload={'text': "y July 1989, Gandhi had won eight national awards. In 1991, following the assassination of Rajiv G